export const pizzaIngredients = [
    {
        id: 'ingredient-1',
        name: 'olive',
        pieceImg: require('../../assets/ingredients/olive.png'),
        portionImg: require('../../assets/pizza/olive.png'),
        weight: 0.1,
        price: 0.3,
        type: 'ingredient',
        quantity: 0,
    },
    {
        id: 'ingredient-2',
        name: 'tomato',
        pieceImg: require('../../assets/ingredients/tomato.png'),
        portionImg: require('../../assets/pizza/tomato.png'),
        weight: 0.3,
        price: 0.2,
        type: 'ingredient',
        quantity: 0,
    },
    {
        id: 'ingredient-3',
        name: 'greens',
        pieceImg: require('../../assets/ingredients/greens.png'),
        portionImg: require('../../assets/pizza/greens.png'),
        weight: 0.05,
        price: 0.1,
        type: 'ingredient',
        quantity: 0,
    },
    {
        id: 'ingredient-4',
        name: 'mashrooms',
        pieceImg: require('../../assets/ingredients/mashrooms.png'),
        portionImg: require('../../assets/pizza/mashrooms.png'),
        weight: 0.1,
        price: 0.5,
        type: 'ingredient',
        quantity: 0,
    },
    {
        id: 'ingredient-5',
        name: 'sausage',
        pieceImg: require('../../assets/ingredients/sausage.png'),
        portionImg: require('../../assets/pizza/sausage.png'),
        weight: 0.3,
        price: 0.5,
        type: 'ingredient',
        quantity: 0,
    },
];

export const pizzaBaseSizes = [
    {
        id: 'base-1',
        name: 'SMALL',
        size: 0.9,
        weight: 0.2,
        price: 1,
        type: 'base',
        selected: false,
        quantity: 1,
    },
    {
        id: 'base-2',
        name: 'MEDIUM',
        size: 1,
        weight: 0.4,
        price: 2,
        type: 'base',
        selected: true,
        quantity: 1,
    },
    {
        id: 'base-3',
        name: 'BIG',
        size: 1.1,
        weight: 0.6,
        price: 3,
        type: 'base',
        selected: false,
        quantity: 1,
    },
];
